# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.cache/wt} [current_project]
set_property parent.project_path {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/ALU.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/Anode.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/BitShifter.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Bitshiftleft.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Bitshiftright.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/CMP.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Combiner.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Combiner_div.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/DFF.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/Dec_2_to_4.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/Dec_3_to_8.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Decoder_2_to_4.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Decoder_3_to_8.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Divider.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Divider_1bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/FA.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/HA.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/INS_DECO2.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Inverter.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/LUT_16_7.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/sources_1/new/MUX_1_to_2.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/MUX_2_8.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/MUX_2_WAY_4bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_2_to_1.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/sources_1/new/MUX_2_way_4_bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_2_way_8_bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/MUX_2_way_8bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/MUX_4_8.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/MUX_8_8.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_8_way_8_bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Multiplier.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Mux_8_to_1.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/new/NanoProcessorLower.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/new/NanoProcessorUpper.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Out_unit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/PROM.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Power.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Prog_counter.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/RCA.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/RCA8bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/new/RCA_4.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/RCA_8bit.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Reg.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/RegBank.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/sources_1/new/Reset.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Reseter.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/Slow_Clk.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/TWISTER.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/signed_divider.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/imports/new/validator.vhd}
  {D:/Nuthara_N_R/UOM/Academic/Sem 2/CS1050 - Computer Organization and Digital Design/Labs/Lab 09 10/final submission/Lab_10/Lab 10.srcs/sources_1/new/NanoProcessor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
